analysis_type: asimov
llh: SAYLLH
detector_configs: [IC86_pass2_SnowStorm_FTP_HESE_Cascades,IC86_pass2_SnowStorm_FTP_HESE_DoubleCascades,IC86_pass2_SnowStorm_FTP_HESE_Tracks]
input_params:
  gamma_astro: 2.87
  astro_norm: 2.1233
  astro_nue_ratio: 1.0
  astro_nutau_ratio: 1.0
  prompt_norm: 0.0
  conv_norm: 1.0
  # all (other) nuisance parameters at default
